### ISSUE TITLE
文件上传阿里云报错

### ISSUE THREAD

**Issue by 2321605193** [zhxuc/wipi#14]
![image](https://user-images.githubusercontent.com/39330227/79064775-65292280-7cde-11ea-8d24-8901b904d7a8.png)

**Comment by since123** [comment]
贴一下本地启动的服务端的报错。

**Comment by zhxuc** [comment]
本地启动的服务端报错贴一下

**Comment by 2321605193** [comment]
是我OSS配置有误吗？





非常感谢您






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhxuc"<notifications@github.com&gt;; 
发送时间: 2020年4月12日(星期天) 晚上9:40
收件人: "zhxuc/wipi"<wipi@noreply.github.com&gt;; 
抄送: "醉寻す流逝の岁月"<2321605193@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhxuc/wipi] 文件上传阿里云报错 (#14)





 
本地启动的服务端报错贴一下

**Comment by zhxuc** [comment]
我也没看到你有贴图片？你看下 [ali-oss](https://github.com/ali-sdk/ali-oss) 的文档，直接 node 写个脚本看下你填写的 oss 配置能否拉出文件。

```
const client = new OSS({
    region: 'oss-cn-hangzhou',
    accessKeyId: '<access-key-id>',
    accessKeySecret: '<access-key-secret>',
    bucket: '<bucket-name>',
    stsToken: '<security-token>'
  });

  client.list().then((result) => {
    console.log('objects: %j', result.objects);
    return client.put('my-obj', new OSS.Buffer('hello world'));
  }).then((result) => {
    console.log('put result: %j', result);
    return client.get('my-obj');
  }).then((result) => {
    console.log('get result: %j', result.content.toString());
  });
```

**Comment by 2321605193** [comment]
错误找出来了
![image](https://user-images.githubusercontent.com/39330227/79089678-8db22a80-7d79-11ea-8774-b65f2f880ec5.png)

serve报错
![image](https://user-images.githubusercontent.com/39330227/79089702-a3275480-7d79-11ea-96d8-55bbc809f72d.png)
bucket必须符合规范

脚本的执行结果是这样的
![image](https://user-images.githubusercontent.com/39330227/79089749-d7027a00-7d79-11ea-9ce2-fc03dbbfcd7b.png)
您试图访问的bucket必须使用指定的端点寻址。请将所有未来的请求发送到此终结点。

我不知道这个端点寻址是什么？

不是阿里云上的这个地址吗

![image](https://user-images.githubusercontent.com/39330227/79089807-0f09bd00-7d7a-11ea-8378-1d1449f4d5e2.png)

感谢您的耐心回复

**Comment by zhxuc** [comment]
我猜 `bucket` 应该是 `falcon520`，那上面已经写了是 `Bucket 域名`，这里要填的是 `Bucket 名字`。

**Comment by 2321605193** [comment]
确实是的，已经上传成功，感谢您
