### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by 2321605193** [zhxuc/wipi#15]
1、评论发表后可以刷新一下页面
2、文章发表后，可以跳到预览页或者后台首页或者给提示是继续发表还是去预览
我只是感觉这两个操作做完成功后还是留在可编辑状态有点奇怪

**Comment by zhxuc** [comment]
1. client 的评论框有些 bug，会修复的。因为评论需要审核才能显示，也可以看到提示了『评论已提交审核』，所以我认为没必要刷新页面。
2. 打算改成文章发布后，关闭编辑器，返回首页。
