### ISSUE TITLE
更新操作有点看不明啊

### ISSUE THREAD

**Issue by yangcecode** [zhxuc/wipi#7]
let hashNewPassword = User.encryptPassword(newPassword);
    const newUser = await this.userRepository.merge(existUser, {
      password: hashNewPassword,
    });
    return this.userRepository.save(newUser);

**Comment by zhxuc** [comment]
密码都会进行加密，这里是对明文新密码加密后进行存储。这样存到数据库的密码都是加密后的。

**Comment by yangcecode** [comment]
> 密码都会进行加密，这里是对明文新密码加密后进行存储。这样存到数据库的密码都是加密后的。

可以加你个好友 或者qq群吗 向你请教下

**Comment by zhxuc** [comment]
wechat：kaivn07
